### ISSUE TITLE
Best way to handle events that are too large for buffering

### ISSUE THREAD

**Issue by rmelick** [fluent/fluent-logger-java#56]
When looking through RawSocketSender to troubleshoot our other issue (see comment on #18), I noticed that RawSocketSender does not handle large events very well in send().  It assumes that flush() always makes enough capacity in the pendings buffer to save the new bytes.  If the event was bigger than the buffer, you get a BufferOverflowException.

```
java.nio.BufferOverflowException
	at java.nio.HeapByteBuffer.put(HeapByteBuffer.java:189)
	at java.nio.ByteBuffer.put(ByteBuffer.java:859)
	at org.fluentd.logger.sender.RawSocketSender.send(RawSocketSender.java:171)
```

Also, if every log message you send is larger than the buffer, then the RawSocketSender will attempt to flush to the socket on every message.

Is this the desired behavior?  I could imagine adding a size check to the send() method that immediately returns false if the event is too large, to avoid the BufferOverflowException.  What is the normal way of handling errors in RawSocketSender?

**Comment by kidnan1991** [comment]
@rmelick 
it is nearly 4 years since then. AFAIK, if you can predict the log message size is bigger than buffer size then you can specific the size when you create the FluentLogger.getLogger()
` FluentLogger getLogger(String tagPrefix, String host, int port, int timeout, int bufferCapacity)`
