### ISSUE TITLE
Connection Reset on calling Fluentlogger.log()

### ISSUE THREAD

**Issue by sharadkejriwal** [fluent/fluent-logger-java#86]
I am getting below error on calling fluentlooger.log(). This is not occurring always but is happening frequently and I am not getting all of my logs.  I am using version 0.3.3.

ERROR RawSocketSender: org.fluentd.logger.sender.RawSocketSender
java.net.SocketException: Connection reset
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:115)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:155)
	at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
	at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
	at org.fluentd.logger.sender.RawSocketSender.flush(RawSocketSender.java:196)
	at org.fluentd.logger.sender.RawSocketSender.send(RawSocketSender.java:184)
	at org.fluentd.logger.sender.RawSocketSender.emit(RawSocketSender.java:149)
	at org.fluentd.logger.sender.RawSocketSender.emit(RawSocketSender.java:131)
	at org.fluentd.logger.sender.RawSocketSender.emit(RawSocketSender.java:126)
	at org.fluentd.logger.FluentLogger.log(FluentLogger.java:101)
	at org.fluentd.logger.FluentLogger.log(FluentLogger.java:86)

What can be the reason?? How to fix?

**Comment by komamitsu** [comment]
I guess the TCP port Fluentd's in_forward plugin listened was close somehow. Did you check Fluentd's log messages?

**Comment by sharadkejriwal** [comment]
The error was "BufferQueueLimitError" as below:
2019-04-24 14:04:00 +0000 [error]: forward error error=#<Fluent::BufferQueueLimitError: queue size exceeds limit> error_class=Fluent::BufferQueueLimitError
  2019-04-24 14:04:00 +0000 [error]: suppressed same stacktrace
2019-04-24 14:04:00 +0000 [warn]: emit transaction failed: error_class=Fluent::BufferQueueLimitError error="queue size exceeds limit" tag="mdsdlog.testlog"
  2019-04-24 14:04:00 +0000 [warn]: suppressed same stacktrace

Increasing the buffer size parameters in the config solved the issue.

**Comment by Jump-Boy** [comment]
Want to ask, I also report 'java.net.SocketException: Connection reset'. 
I am k8s pod , I have configured '<system> log_level debug </system>' in fluentd.conf , but there's nothing else except this '[debug]: #0 connect new socket'
fluentd version: v1.14.0-debian
